eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${eureka_url:http://192.168.0.69:8761/eureka}
      # defaultZone: http://localhost:9000/eureka/
  instance:
    hostname: localhost
